# name: "debug_evals"
ckpt_dir: "/home/kieron/fyp/blt/hf-weights/blt_1b"
dump_dir: "/home/kieron/fyp/blt/dump-dir"
entropy_ckpt_dir: "/home/kieron/fyp/blt/hf-weights/entropy_model"
generator:
  max_tokens: 4096
  dtype: bf16
  temperature: 1.0
  top_p: 0.95
harness:
  tasks:
    # - hellaswag
    - piqa
    # - arc_easy
    # - arc_challenge
    # - mmlu
    # - mbpp
    # - humaneval
    # - task: boolq
    #   dataset_kwargs:
    #     trust_remote_code: true
    # - task: nq_open
    #   num_fewshot: 5
    # - task: social_iqa
    #   dataset_kwargs:
    #     trust_remote_code: true
    # - triviaqa
    # - winogrande
    # - openbookqa
    # - race
    # - commonsense_qa
    # - coqa
    # - copa
    # - gsm8k
    # - bbh
    # - mmlu_pro
# validation:
#   max_steps: 1000