ckpt_dir: "/scratch/Projects/CFP-01/CFP01-CF-060/kieron/blt/hf-weights/blt_1b"
# ckpt_dir: "/scratch/Projects/CFP-01/CFP01-CF-060/kieron/blt/tmp/blt-1b/"
dump_dir: "/scratch/Projects/CFP-01/CFP01-CF-060/kieron/blt/dump-dir"
entropy_ckpt_dir: "/scratch/Projects/CFP-01/CFP01-CF-060/kieron/blt/hf-weights/entropy_model"
# entropy_ckpt_dir: "/scratch/Projects/CFP-01/CFP01-CF-060/kieron/blt/blt-entropy/50m_mC4"
generator:
  max_tokens: 2048
  dtype: bf16
  temperature: 0.0
  top_p: 0.95
harness:
  tasks:
    # - hellaswag
    # - piqa
    # - arc_easy
    # - arc_challenge
    # - mmlu
    - task: mbpp
      # generation_kwargs:
      #   max_length: 1024
    - task: humaneval
      # generation_kwargs:
      #   max_length: 512
    # - task: boolq
    #   dataset_kwargs:
    #     trust_remote_code: true
    # - task: nq_open
    #   num_fewshot: 5
    # - task: social_iqa
    #   dataset_kwargs:
    #     trust_remote_code: true
    # - triviaqa
    # - winogrande
    # - openbookqa
    # - race
    # - commonsense_qa
    # - coqa
    # - copa
    # - gsm8k
    # - bbh
    # - mmlu_pro
# validation:
#   max_steps: 1000